name: metzabook
description: "Sistema de control inteligente Metzabook (Bluetooth + WiFi)"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Bluetooth Clásico (El que necesitas para tu código de Arduino actual)
  
  # Bluetooth Low Energy (Opcional, pero bueno tenerlo)
  flutter_blue_plus: ^1.31.0
  
  # Utilidades y Permisos
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  http: ^1.2.0
  esp_smartconfig: ^3.0.0
  url_launcher: ^6.1.10
  another_telephony: ^0.4.1
  bluetooth_classic: ^0.0.4
  nsd: ^4.1.0
  web_socket_channel: ^2.4.0


dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Ajustado a una versión más estándar para tu SDK

flutter:
  uses-material-design: true
  assets:
    - assets/chapingo_logo.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/metzabook.png"
